### ISSUE TITLE
Running error:

### ISSUE THREAD

**Issue by Anonymouszj** [zasdfgbnm/TorchSnooper#7]
PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check:
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "D:\Anaconda\envs\pytorch10\lib\site-packages\pysnooper\tracer.py", line 272, in __exit__
    sys.settrace(stack.pop())

**Comment by Anonymouszj** [comment]
If I comment out sys.settrace(stack.pop()) ，it will be OK.

**Comment by zasdfgbnm** [comment]
I think this is because [PySnooper](https://github.com/cool-RR/PySnooper) is not designed to be used together with a debugger. I think this is not a TorchSnooper issue, but a PySnooper issue.

You can check by replacing `torchsnooper.snoop()` with `pysnooper.snoop()`, and you should see the same error.
